### ISSUE TITLE
Create an example theme with SCSS scaffolding, so that we can have semantic and clean styles.

### ISSUE THREAD

**Issue by emarchak** [myplanetdigital/drupal-skeletor#31]
**Request**: Each project we build has a custom theme, and we use similar patterns for each. Create a custom theme with the basic things we need such as a libaries.yml, a way to organize preprocess + twig files, and some SCSS scaffolding so we know how to organize the styles for the project.

**Reading**: Using Drupal Console to generate a theme, BEM (or other methods), Drupal 8 Theme Libraries. Talk to Rene and Jerry, too!

**Comment by nedatrifkovic** [comment]
### Drupal 8 Theme

The new base theme that we can use for upcoming Drupal 8 projects that will be based on the Skeletor profile can be called **skeletor**. 

This new theme can either:
- be fully custom and define all elements, styles and functionalities, or 
- it can be a subtheme based off of an already existing solution (Omega, Bootstrap etc.).

#### Proposed file  structure

|-config
|    |-install
|    |    |-themename.settings.yml
|    |-schema
|    |    |-themename.schema.yml
|-css
|    |-style.css
|    |-**any other css file**
|-js
|    |-themename.js
|-images
|    |-**any image asset**
|-includes
|    |-**example: bootstrap js and/or css files**
|-preprocess
|    |-preprocess-views.inc
|    |-preprocess-page.inc
|    |-preprocess-node.inc
|-theme
|    |-theme.menu-links.inc
|    |-theme.html-tag.inc
|-sass
|    |-style.scss
|    |-**any additional scss files**
|-templates
|    |-block.html.twig
|    |-comment.html.twig
|    |-html.html.twig
|    |-maintenance-page.html.twig
|    |-node.html.twig
|    |-page.html.twig
|-config.rb
|-favicon.ico
|-logo.png
|-screenshot.png
|-themename.breakpoints.yml
|-themename.info.yml
|-themename.libraries.yml
|-themename.theme

#### Theme structure

Explanation on the files and folders that comprise theme structure:

- **config** 
	- this folder is optional and 
- **.info.yml** 
	- this mandatory file gives information about your theme
- **.libraries.yml**
	- defines your libraries (mostly your JS, CSS files).
- **.breakpoints.yml**
	- defines the points to fit different screen devices.
- **themename.theme**
	- The PHP file that stores conditional logic and data preprocessing of the variables before they are merged with markup inside the .html.twig file.
- **/sass**
	- Compass files that will be converted to CSS files.
- **/css**
	- where your css files lay. Must be defined in the info, and libraries file to operate.
- **/js**
	- where your js files lay. Must be defined in the info, and libraries file to operate.
- **/images**
	- where you theme images are stored. It is a good practice to put images in this folder.
- **/includes**
	- where 3rd-parties libraries (like Bootstrap, Foundation, Font Awesome,etc) are put. It is a good practice to store them in this folder
- **/preprocess**
	- Includes PHP files that serve purpose of preprocessing various page elements (page/views/fields/nodes etc.).
- **/theme**
	- Includes any theme hooks in it's own separate .inc files.
- **/templates**
	- where all your template files (ones that provide html markup of your theme page) are placed.
- **logo.png**
	- your theme logo if you're using one.
- **favicon.ico**
	- your theme favicon if you're using one.
- **screenshot.png**
	- your theme screenshot that will be displayed in the admin/appereance.

#### YML files

There are several *.yml files being used in the new theme.

##### Themename.info.yml

```yml
name: **Theme name** Theme
description: 'Drupal 8 theme.'
base theme: **(base theme | false)**
package: **package name**
type: theme
version: 1.0
core: 8.x

regions:
      headline: headline
      header: header
      content: content
      sidebar: sidebar
      footer: Footer
```

##### Themename.libraries.yml

```yml
global-styling:
   version: VERSION
   css:
     theme:
       includes/bootstrap/css/bootstrap.css: {}
       css/style.css: {}
   js:
     theme:
	   js/themename.js
	 dependencies
	    core/jquery  
```

##### config.rb

```rb
# We tell compass that we want to use. SCSS format in this case
preferred_syntax = :scss

# Where we want our CSS files to go
css_dir = 'css'

# Where we want to put our source SASS Files
sass_dir = 'sass'

# While in Dev, we can use this feature to easily debug the CSS styles
line_comments = true
```

#### References

- https://www.drupal.org/docs/8/theming
- https://www.weebpal.com/blog/how-create-drupal-8-theme-scratch
- https://www.drupal.org/docs/8/theming-drupal-8/creating-advanced-theme-settings
- https://drupalize.me/series/drupal-8-theming
- https://sqndr.github.io/d8-theming-guide/
- https://www.lullabot.com/articles/drupal-8-theming-fundamentals-part-1
- https://evolvingweb.ca/blog/setting-up-sass-compass-for-your-drupal-8-theme
